// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/timeplus-io/terraform-provider-timeplus/internal/timeplus"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &dashboardDataSource{}

func NewDashboardDataSource() datasource.DataSource {
	return &dashboardDataSource{}
}

// dashboardDataSource defines the data source implementation.
type dashboardDataSource struct {
	client *timeplus.Client
}

// dashboardDataSourceModel describes the data source data model.
type dashboardDataSourceModel dashboardResourceModel

func (d *dashboardDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dashboard"
}

func (d *dashboardDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "A dashboard is a set of one or more panels organized and arranged in one web page. A variety of panels are supported to make it easy to construct the visualization components so that you can create the dashboards for specific monitoring and analytics needs.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The dashboard immutable ID, generated by Timeplus",
				Required:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The human-friendly name for the dashboard",
				Computed:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "A detailed text describes the dashboard",
				Computed:            true,
			},
			"panels": schema.StringAttribute{
				MarkdownDescription: "A list of panels defined in a JSON array. The best way to generate such array is to copy it directly from the Timeplus console UI.",
				Computed:            true,
			},
		},
	}
}

func (d *dashboardDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*timeplus.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *timeplus.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *dashboardDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *dashboardDataSourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	s, err := d.client.GetDashboard(data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Dashboard",
			fmt.Sprintf("Unable to read dashboard %q, got error: %s",
				data.Name.ValueString(), err))
		return
	}

	data.Name = types.StringValue(s.Name)
	data.Description = types.StringValue(s.Description)

	bytes, err := json.Marshal(s.Panels)
	if err != nil {
		resp.Diagnostics.AddAttributeError(path.Root("panels"), "Panel Parsing Failed", err.Error())
	}

	data.Panels = types.StringValue(string(bytes))

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
