// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/timeplus-io/terraform-provider-timeplus/internal/timeplus"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &sourceDataSource{}

func NewSourceDataSource() datasource.DataSource {
	return &sourceDataSource{}
}

// sourceDataSource defines the data source implementation.
type sourceDataSource struct {
	client *timeplus.Client
}

// sourceDataSourceModel describes the data source data model.
type sourceDataSourceModel sourceResourceModel

func (d *sourceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_source"
}

func (d *sourceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "Timeplus sources run queries in background and send query results to the target system continuously.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The source immutable ID, generated by Timeplus",
				Required:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The human-friendly name for the source",
				Computed:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "A detailed text describes the source",
				Computed:            true,
			},
			"stream": schema.StringAttribute{
				MarkdownDescription: "The target stream the source ingests data to",
				Computed:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "The type of the source, refer to the Timeplus document for supported source types",
				Computed:            true,
			},
			// since Terraform does not have built-in support for map[string]any with the framework library, we use JSON as a simple solution
			"properties": schema.StringAttribute{
				MarkdownDescription: "JSON string of an object defines the configurations for the specific source type. The properites could contain sensitive information like password, secret, etc.",
				Sensitive:           true,
				Computed:            true,
			},
		},
	}
}

func (d *sourceDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*timeplus.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *timeplus.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *sourceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *sourceDataSourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	s, err := d.client.GetSource(data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Source",
			fmt.Sprintf("Unable to read source %q, got error: %s",
				data.Name.ValueString(), err))
		return
	}

	data.Name = types.StringValue(s.Name)
	data.Description = types.StringValue(s.Description)
	data.Stream = types.StringValue(s.Stream)
	data.Type = types.StringValue(s.Type)

	propsBytes, err := json.Marshal(s.Properties)
	if err != nil {
		resp.Diagnostics.AddError("Bad Source Properties", fmt.Sprintf("Unable to encode source properties into JSON, got error: %s", err))
		return
	}
	data.Properties = types.StringValue(string(propsBytes))

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
